### ISSUE TITLE
Potential race condition with dropIfExistsByKey

### ISSUE THREAD

**Issue by pshirshov** [xerial/sbt-sonatype#101]
Hi once again,

I'm not sure if it's a real problem, though seems like you are dropping all the staging repositories when `sonatypeBundleRelease` starts working.

In case that's true - it's an issue. For example we run two parallel jobs to publish izumi for 2.12 and 2.13, so there is a chance that the jobs may interfere.

**Comment by pshirshov** [comment]
Okay, I guess `sonatypeSessionName` solves my problem

**Comment by xerial** [comment]
It depends whether you are sharing the same working folder for 2.12 and 2.13 build. 

If you are sharing the working folder:
- Run two publishSigned tasks for Scala 2.12 and Scala 2.13 in parallel
- Finally run sonatypeBundleRelease

If you are not sharing any working folder for cross builds and you still want to use bundle upload, run the following steps for each cross build:
- Set sonatypeSessionName := s"[sbt-sonatype] ${name.value} ${scalaBinaryVersion.value}_${version.value}"
- publishSigned
- sonatypeBundleRelease

**Comment by xerial** [comment]
Added a note for such build configurations https://github.com/xerial/sbt-sonatype/commit/a14eecfdc711cba87759e7ce55c9fdbf4a979f5b
