### ISSUE TITLE
Wrong sonatypeProfileName value provided for the sonatypeBundleRelease command

### ISSUE THREAD

**Issue by plokhotnyuk** [xerial/sbt-sonatype#109]
It worked fine for sbt-sonatype v2.5 or earlier version. 

But after migration to v3.7 and switching to the `sonatypeBundleRelease` command (instead of `sonatypeReleaseAll`) the [provided value of `sonatypeProfileName`](https://github.com/plokhotnyuk/jsoniter-scala/blob/59c4db87ee684dd71e52d39c22acceb9fdcb2d7c/build.sbt#L53) started to be ignored:
```
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = com.github.plokhotnyuk.jsoniter-scala
[info] Preparing a new staging repository for [sbt-sonatype] jsoniter-scala 0.55.3
[info] Reading staging repository profiles...
[info] Reading staging profiles...
[info] No staging repository for [sbt-sonatype] jsoniter-scala 0.55.3 is found
[error] java.lang.IllegalArgumentException: Profile com.github.plokhotnyuk.jsoniter-scala is not found. Check your sonatypeProfileName setting in build.sbt
```

**Comment by plokhotnyuk** [comment]
Changing of `organization` to `com.github.plokhotnyuk` is not W/A for my case...

**Comment by xerial** [comment]
So it means you want to set 
```scala
sonatypeProfileName := “com.github.plokhotnyuk”
```
?

**Comment by xerial** [comment]
The code reading this setting is like this: https://github.com/xerial/sbt-sonatype/blob/master/src/main/scala/xerial/sbt/Sonatype.scala#L372

Possibility includes:
- You might have old `profileName` settings somewhere. 
- sonatypeProfileName is not defined at the root project. (ThisBuild / sonatypeProfileName) := ... 

Could you show me your build.sbt or the result of running `sbt “show sontaypeProfileName”` ?

**Comment by plokhotnyuk** [comment]
@xerial thank you a lot!

In last commit I'd moved most settings to the root (including `sonatypeProfileName`) and it worked for me.
