### ISSUE TITLE
Configuring timeout

### ISSUE THREAD

**Issue by exoego** [xerial/sbt-sonatype#133]
I am publishing 400+ artifacts in single sbt project (200 artifacts x 2 Scala major versions).

Thanks to the recently-added feature `sonatypeBundleRelease`, uploading time was reduced dramatically !! (from several hours to minutes).

However, at the end of release process, I found that waiting `close` operation occasionally get timeout (actually, `close` operation completeded successfully on Sonatype).

It would be nice if timeout is configurable so one can increase it like 30 minutes, 2 hour, or whatever.

**Comment by Atry** [comment]
Unlike traditional releases,  bundle releases do not retry. That's why it results timeout.

**Comment by xerial** [comment]
sbt-sonatype-3.9.1 added sonatypeTimeoutMillis, the default of which is 1 hour. I think this will solve the issue.
