### ISSUE TITLE
Retry on 500 error

### ISSUE THREAD

**Issue by xerial** [xerial/sbt-sonatype#16]
We need to retry sonatypeRelease command on the following error:
```
[trace] Stack trace suppressed: run last *:sonatypeReleaseAll for the full output.
[error] (*:sonatypeReleaseAll) java.io.IOException: Failed to retrieve data from /staging/repository/orgxerial-1099/activity: HTTP/1.1 500 Server Error
```

**Comment by xerial** [comment]
Fixed in e3090aad2bc5112b65c330ae0aeb1267c12f74d1

**Comment by jvican** [comment]
Is it normal to get 500 error all the time?

**Comment by xerial** [comment]
500 (service internal error) means there is something wrong in sonatype API side.

**Comment by jvican** [comment]
Thank you @xerial. Maybe I have to ping Joel if it's my first release? They probably need to turn some knobs in the Sonatype side to open Central for me...
