### ISSUE TITLE
Support for scala 2.11

### ISSUE THREAD

**Issue by magnusart** [xerial/sbt-sonatype#17]
Hi

I just had a look at old issue and there it said you had a release for 2.11. But looking here I can only find max 2.10 releases:
https://repo1.maven.org/maven2/org/xerial/sbt/

Would you consider releasing for 2.11?

**Comment by xerial** [comment]
Do you want to use Scala 2.11 with sbt-0.13.x? Unfortunately, sbt-0.13.x still needs Scala 2.10.x. 

But sbt-sonatype can be used for publishing Scala 2.11 projects with sbt-0.13.x.
