### ISSUE TITLE
Augment the plugin to support additional Nexus Staging REST APIs

### ISSUE THREAD

**Issue by NicolasRouquette** [xerial/sbt-sonatype#21]
Nexus supports several staging workflow scenarios as described here:
https://github.com/sonatype/nexus-maven-plugins/blob/master/staging/maven-plugin/WORKFLOWS.md

Currently, the plugin supports most of the Sonatype Nexus Staging Plugin REST APIs except for staging profile creation: [/staging/profiles/{profileIdKey}/start](https://oss.sonatype.org/nexus-staging-plugin/default/docs/path__staging_profiles_-profileIdKey-_start.html)

**Comment by xerial** [comment]
Merged #22
