### ISSUE TITLE
add support for staging repository description PUT/GET

### ISSUE THREAD

**Issue by NicolasRouquette** [xerial/sbt-sonatype#23]
According to Sonatype:

The request to update a staging repository's description is a PUT request to:

`http://{nexus-host}/nexus/service/local/staging/repository/{repository-id}`

The payload looks like this:

```
{"repositoryId":"<insert staging repository id here>","description":"<insert current description here to preserve it>"}
```

Make a GET call first to get the existing description value.

**Comment by xerial** [comment]
Since sbt-sonatype 3.0, we are using this description part as identifiers of staging repositories. So we will not support PUT operation to change the description.
