### ISSUE TITLE
sonatypeRelease error with worng nexus URL

### ISSUE THREAD

**Issue by hagay3** [xerial/sbt-sonatype#231]
After executing publishSigned everything working fine and artifacts released to the right nexus server which is:
https://s01.oss.sonatype.org/

But while executing sonatypeRelease I get an error:

```
sbt:root> sonatypeRelease
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = io.github.hagay3
[info] Reading staging repository profiles...
[error] java.lang.IllegalStateException: No credential is found for oss.sonatype.org. Prepare ~/.sbt/(sbt_version)/sonatype.sbt file.
[error] Use 'last' for the full log.
```

build.sbt:
https://github.com/hagay3/skuber/blob/f1a6b14a5b9a987ea43f9eeec572f87508d739ba/build.sbt

~/.sbt/1.0/sonatype.sbt:
```
credentials += Credentials("Sonatype Nexus Repository Manager",
        "s01.oss.sonatype.org",
        "hagay3",
        "***********")
```

**Comment by xerial** [comment]
Do you have this setting? 
```scala
ThisBuild / sonatypeCredentialHost := "s01.oss.sonatype.org"
```

**Comment by hagay3** [comment]
@xerial 
Thank you for your response,
And yes I have this setting in here
https://github.com/hagay3/skuber/blob/f1a6b14a5b9a987ea43f9eeec572f87508d739ba/build.sbt#L44

**Comment by xerial** [comment]
@hagay3 It seems you are using an old version of sbt-sonatype. Try the latest version

**Comment by xerial** [comment]
Reopen the issue if you still have this problem after upgrading sbt-sonatype version
