### ISSUE TITLE
Can not set sonatypeProfileName

### ISSUE THREAD

**Issue by sagifogel** [xerial/sbt-sonatype#232]
Hi,

I'm having trouble deploying to https://s01.oss.sonatype.org.
I tried using these lines:
ThisBuild / sonatypeProfileName: = "io.github.sagifogel"
ThisBuild / sonatypeCredentialHost: = Sonatype.sonatype01
ThisBuild / sonatypeRepository: = s "https: // $ {Sonatype.sonatype01} / service / local"

But somehow the default sonatype repository https://oss.sonatype.org/service/local is used.

[Tag](https://github.com/sagifogel/Proptics/runs/2521718195?check_suite_focus=true)
[Snapshot](https://github.com/sagifogel/Proptics/runs/2521628533?check_suite_focus=true)

This is my [repository](https://github.com/sagifogel/Proptics) 
This is my [sonatype jira](https://issues.sonatype.org/browse/OSSRH-66317?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel) ticket

Thank you very much.

**Comment by xerial** [comment]
I'm not sure how sbt-ci-release uses sbt-sonatype, but at least you can check the setting by running sonatypeRespository command:
```
$ sbt
> sonatypeRepository 
```

For some reason, your project uses the default one for all projects:
```
sbt:proptics> sonatypeRepository
[info] coreJVM / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] lawJVM / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] testJVM / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] example / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] profunctorJVM / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] propticsJVM / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] coreJS / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] profunctorJS / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] lawJS / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] testJS / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] propticsJS / sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
[info] sonatypeRepository
[info] 	https://oss.sonatype.org/service/local
```

**Comment by sagifogel** [comment]
It worked, thank you very much.
Unfortunately I have another  problem.

profile-target-matching-staging, failureMessage:Profile target mismatch: /com/github/sagifogel/proptics-core_sjs1_2.12/0.1.0/proptics-core_sjs1_2.12-0.1.0-javadoc.jar.asc.md5

[https://github.com/sagifogel/Proptics/runs/2522393306?check_suite_focus=true](
https://github.com/sagifogel/Proptics/runs/2522393306?check_suite_focus=true)

Thanks.

**Comment by sagifogel** [comment]
@xerial  can you please help?
Thanks.

**Comment by xerial** [comment]
You need to fix your organization setting in your build.sbt. For example, you are explicitly setting `com.github.sagifogel`
at https://github.com/sagifogel/Proptics/blob/master/build.sbt#L8

But your sonatype profile name is io.github.saigfogel, so Sonatype always rejects releasing artifacts other than under `io.github.saigfogel`

**Comment by sagifogel** [comment]
It worked.
Thank you very much for your help.
