### ISSUE TITLE
error [Sonatype] [MISSING_PROFILE] Profile winitzki is not found. Check your sonatypeProfileName setting in build.sbt  - (Sonatype.scala:425)

### ISSUE THREAD

**Issue by winitzki** [xerial/sbt-sonatype#249]
**Describe the bug**
Cannot do sonatype commands due to "profile not found" - I wish the error message were more clear.

**How to reproduce the issue**
I am not able to publish my open-source project - [https://github.com/Chymyst/curryhoward](https://github.com/Chymyst/curryhoward) to Sonatype (but this worked around 3 years ago). I am publishing from the master branch and trying to use the latest versions of everything. Publishing commands are:

```
$ sbt
sbt> project curryhoward
sbt:curryhoward> +publishSigned
sbt:curryhoward> sonatypeBundleRelease
```

This fails at the last step with the output:

```
2021-08-23 12:30:31.832+0200  info [SonatypeService] sonatypeRepository  : https://oss.sonatype.org/service/local  - (SonatypeService.scala:23)
2021-08-23 12:30:31.841+0200  info [SonatypeService] sonatypeProfileName : winitzki  - (SonatypeService.scala:24)
[info] Preparing a new staging repository for [sbt-sonatype] curryhoward 0.3.8
2021-08-23 12:30:31.846+0200  info [SonatypeClient] Reading staging repository profiles...  - (SonatypeClient.scala:108)
2021-08-23 12:30:34.672+0200  info [SonatypeService] No previous staging repository for [sbt-sonatype] curryhoward 0.3.8 was found  - (SonatypeService.scala:96)
2021-08-23 12:30:34.673+0200 error [Sonatype] [MISSING_PROFILE] Profile winitzki is not found. Check your sonatypeProfileName setting in build.sbt  - (Sonatype.scala:425)
```

I have credentials set up in $HOME/.sbt/1.0/sonatype.sbt and I have gpg keyring set up. I have `publishTo := sonatypePublishToBundle.value` in my build.sbt. `+publishSigned` works. But `sonatypeBundleRelease` gives the error "Profile winitzki not found". The same error happens with all other `sonatypeXYZ` commands. My sonatype profile is active, I am able to log in to oss.sonatype.org and see my previous releases. 

- sbt version: 1.5.5
- sbt-sonatype version: 3.9.7
- Show your build settings:
```
$ sbt
> sonatypeProfileName
[info] winitzki
> sonatypeRepository
[info] https://oss.sonatype.org/service/local
```
- GitHub repository: (Having a GitHub repository for reproducing the issue would be helpful)
[https://github.com/Chymyst/curryhoward](https://github.com/Chymyst/curryhoward)

**Additional context**
I am writing here because I cannot understand what is happening and cannot find any help about this error. I used to be able to publish my open-source project to sonatype using this plugin. A screenshot showing my sonatype profile is attached. My sonatype account was made in 2017 and has not been changed since then (so the authentication with s01.oss.sonatype.org is not an issue). I tried to use that authentication but it does not work, failing with `401 Unauthorized`.  Authentication with oss.sonatype.org is working normally, it's not the issue here.

**Comment by winitzki** [comment]
Here is a screenshot of my sonatype profile.
<img width="742" alt="Screen Shot 2021-08-23 at 12 48 30 PM" src="https://user-images.githubusercontent.com/2163489/130438492-c24ccdd5-af27-4187-8f11-00c5425323ee.png">

**Comment by xerial** [comment]
sonatypeProfileName should be a domain name prefix (e.g., org.xxx, com.github.xxx, etc.)

**Comment by xerial** [comment]
It has not been changed at all. The user name should be set at Credential https://github.com/xerial/sbt-sonatype#homesbtsbt-version-013-or-10sonatypesbt
