### ISSUE TITLE
do not set publishTo by default

### ISSUE THREAD

**Issue by cvogt** [xerial/sbt-sonatype#28]
I used to have this plugin in my global config until I realized that it overrides the publishTo I have setup for my individual projects to point to sonatype. That's not desirable for me. I only want the sonatype commands, but decide depending on the project if I publish repositories to sonatype, bintray or other places.

**Comment by xerial** [comment]
Thanks for the feedback. I didn't notice that the global plugin (e.g., specified in ~/.sbt/0.13/plugins/...) have higher precedence than the project settings. Is it true? 

If so, we should let sbt-sonatype users manually set `publishTo`.

**Comment by cvogt** [comment]
seems to be the case. @eed3si9n?

Setting manually seems safer.

**Comment by eed3si9n** [comment]
If you're using the auto plugin correctly, and not doing the `Project(..., settings = ...)` , the user-defined settings should be ordered after the auto plugin's settings.

**Comment by cvogt** [comment]
@eed3si9n correctly on the side of the plugin author or user? I as the user just added it via addPlugin to my global plugins.sbt, nothing else, so I suppose it must be on the plugins side.

Also if I have a multi project built, one sub-project configured to deploy to bintray and nothing configure for the others, would a publish on the root project deploy my other sub-projects to sonatype then? Sounds not ideal. @xerial how about making publishTo a manual opt-in?

**Comment by xerial** [comment]
It looks like a newly added code in sbt-sonatype 1.1, which updates `publishTo` might be related https://github.com/xerial/sbt-sonatype/blob/master/src/main/scala/xerial/sbt/Sonatype.scala#L124.

@cvogt 
Does the same problem happen if you use sbt-sonatype 1.0?

**Comment by cvogt** [comment]
@xerial I was actually using 0.5.1, but confirmed the same problem also exists with 1.0 and 1.1.

**Comment by eed3si9n** [comment]
@cvogt On the side of the build user. Does your build look like this?

```
val foo = project.settings(publishTo := Some(x))
```

and `Some(x)` is taken over by the setting from a plugin?

**Comment by cvogt** [comment]
It looks like this. Is there a different recommended way to propagate the setting to all sub projects?
```
object MyBuild extends Build {
  override lazy val settings =
    super.settings ++
      Seq(
        publishTo := {
          Some( ... )
        },
        ...
      )
}
```

**Comment by xerial** [comment]
It seems the use of lazy for the settings causes the unintentional overwrite.

**Comment by xerial** [comment]
@cvogt I cannot reproduce this issue: 
```
$ cat build.sbt
publishTo := Some("repo" at "http://some.repo.org")
$ sbt "show publishTo"                                                                                                                                                                                             [9:19:30 Apr 04 2016]
[info] Loading global plugins from /Users/leo/.sbt/0.13/plugins
[info] Set current project to sonatype-test (in build file:/Users/leo/work/git/tmp/sonatype-test/)
[info] Some(repo: http://some.repo.org)

$ cat build.sbt
// publishTo := Some("repo" at "http://some.repo.org")
$ sbt "show publishTo"                                                                                                                                                                                             [9:20:51 Apr 04 2016]
[info] Loading global plugins from /Users/leo/.sbt/0.13/plugins
[info] Set current project to sonatype-test (in build file:/Users/leo/work/git/tmp/sonatype-test/)
[info] Some(sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots)
```

**Comment by eed3si9n** [comment]
@cvogt 

> It looks like this. Is there a different recommended way to propagate the setting to all sub projects?

Make an one-off auto plugin inside `project/*.scala`. http://www.scala-sbt.org/0.13/docs/Organizing-Build.html#Defining+auto+plugins

**Comment by dwijnand** [comment]
Here's an example: https://github.com/sbt/sbt-pgp/blob/v1.0.0/project/Common.scala

**Comment by alexflav23** [comment]
+1 On this, it's still a problem as of the latest release. I cannot add the plugin without having it override all bintray publishing settings for instance.

**Comment by xerial** [comment]
@alexflav23 Does it mean you need to have both sonatype and bintray repositories for publishing? If so I agree with that having pre-defined publishTo is cumbersome.

**Comment by alexflav23** [comment]
Hi @xerial,

No, it means simply including `sbt-sonatype` as an SBT plugin will override any other `publishTo` setting found in the project, so we need to work around it.

For example (here)[https://github.com/outworkers/phantom/blob/develop/project/plugins.sbt#L63], where we toggle an environment variable in the CI server which prevents the build from loading the plugin in the first place, just so we can publish to bintray.

Regards.

**Comment by xerial** [comment]
@alexflav23 Thanks. I got the pain point. sbt plugin should be use safely without such a conditional switch.

**Comment by xerial** [comment]
sbt-sonatype do not set publishTo by default since 2.0.0-M1 (for sbt-1.0.0-M5)

**Comment by cvogt** [comment]
Nice :)!!! Any chance we can get it for sbt 0.13?

**Comment by xerial** [comment]
Now working on cross building sbt plugins.

**Comment by xerial** [comment]
Uploaded sbt-sonatye 2.0.0-M1 for sbt 0.13.x
https://oss.sonatype.org/content/repositories/releases/org/xerial/sbt/sbt-sonatype_2.10_0.13/2.0.0-M1/

**Comment by cvogt** [comment]
awesome, thx so much!
