### ISSUE TITLE
[Question] is there a setting to skip javadoc jars? 

### ISSUE THREAD

**Issue by kailuowang** [xerial/sbt-sonatype#30]
Right now sbt-sonatype requires javadoc jar is available for upload when releasing, is there a way to skip javadocs? There is a weird scaladoc compilation bug on 2.10.6 preventing [cats](http://github.com/typelevel/cats) from generating javadocs.

**Comment by xerial** [comment]
I believe sbt-sonatype do nothing in the build process. If you need to skip javadoc/scaladoc generation in sbt, do something like: http://stackoverflow.com/questions/21461798/how-to-disable-scaladoc-generation-in-dist-task-in-play-2-2-x-using-project-bui

**Comment by kailuowang** [comment]
That's what we did. However the we got this error message after that change:

> [info] Failed: javadoc-staging, failureMessage:Missing: no javadoc jar found in folder '/org/typelevel/cats-laws_sjs0.6_2.10/0.5.0'

i.e. we are not generating the javadoc jar but now it's complaining that it couldn't find the javadoc jar. I understand that sbt-sonatype might not be directly managing which artifacts get uploaded, but I am relatively new to sbt, so any help would be appreciated.

**Comment by xuwei-k** [comment]
http://central.sonatype.org/pages/requirements.html#supply-javadoc-and-sources

> If, for some reason (for example, license issue or it's a Scala project), you can not provide -sources.jar or -javadoc.jar , please make fake -sources.jar or -javadoc.jar with simple README inside to pass the checking.

**Comment by kailuowang** [comment]
thanks very much！@xuwei-k

Closing.

**Comment by ryan-williams** [comment]
per [gitter](https://gitter.im/sbt/sbt?at=5a01d39ad6c36fca31e8e5a9), a good way to do this is:

```scala
sources in (Compile, doc) := Seq()
```

This generates an empty `-javadoc.jar`, which lets `sonatypeRelease` complete successfully

[example in the wild](https://github.com/hammerlab/iterators/blob/master/build.sbt#L10)
