### ISSUE TITLE
No staging repository found

### ISSUE THREAD

**Issue by magnusart** [xerial/sbt-sonatype#31]
When I run `publishSigned` and then `sonatypeReleaseAll` I now get the below after upgrading versions.

`publishSinged` emits no errors and I can see the files in target. Not sure how to continue troubleshooting this.

Using version `sbt-sonatype 1.1` and `sbt-pgp 1.0.0` with `sbt 0.13.11`.

```

sbt-templates> sonatypeReleaseAll
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = org.mollyware
[info] Reading staging repository profiles...
[warn] No staging repository is found. Do publishSigned first.
```

**Comment by magnusart** [comment]
Worth mentioning is that I'm publishing a `SNAPSHOT`-release that I wish to overwrite. I removed snapshot from the version name and then it worked.

**Comment by xerial** [comment]
I haven't expected publishing a snapshot version to Sonatype-release repository. Maybe location to search might have changed. I'll check it.

**Comment by xerial** [comment]
`sonatypeDefaultResolver` setting switches `publishTo` configuration. 
https://github.com/xerial/sbt-sonatype/blob/master/src/main/scala/xerial/sbt/Sonatype.scala#L61

So setting this as follows can be used to publish and release SNAPSHOT versions:
```
sonatypeDefaultResolver := Opts.resolver.sonatypeStaging
```

**Comment by magnusart** [comment]
I actually got this to work. My best guess is that there were some old state generated from a previous version of the plugin interfering. When cleaned up it started working again.

**Comment by xerial** [comment]
Thanks for checking :)
