### ISSUE TITLE
Invalide dependecies

### ISSUE THREAD

**Issue by pprados** [xerial/sbt-sonatype#32]
At time, with just add the sbt plugin, I receive:

[warn]  Note: Unresolved dependencies path:
[warn]          org.apache.httpcomponents:httpclient:4.2.6
[warn]            +- org.xerial.sbt:sbt-sonatype:1.1 (scalaVersion=2.10, sbtVersion=0.13) [warn]            +- default:generator-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: org.apache.httpcomponents#httpclient;4.2.6: not found

**Comment by xerial** [comment]
http://central.maven.org/maven2/org/apache/httpcomponents/httpclient/4.2.6/ is actually present in Maven central. Please reload the dependencies again.
