### ISSUE TITLE
Project does not explicitly define a license

### ISSUE THREAD

**Issue by timperrett** [xerial/sbt-sonatype#33]
Certain source files are commented with the Apache 2.0 license header, but the project itself does not declare the Apache 2.0 license. Regardless of which license the project wishes to use, it should be in the root of the repository in a `LICENSE` text file.

**Comment by xerial** [comment]
I'll add. Thanks

**Comment by xerial** [comment]
done.

**Comment by timperrett** [comment]
Thanks @xerial - removes any ambiguities :-)
