### ISSUE TITLE
SnatypeClient logs not forwarded to sbt client

### ISSUE THREAD

**Issue by adpi2** [xerial/sbt-sonatype#376]
**Describe the bug**
When I trigger `sonatypeBundleRelease` from an sbt client shell (using `sbtn`) I cannot see the logs from `SonatypeClient`. All I see is:
```
sbt:root> sonatypeBundleRelease
[info] Preparing a new staging repository for [sbt-sonatype] root 3.0.4
[info] Updating sonatypePublishTo settings...
[info] Welcome to scala-debug-adapter 3.0.4
sbt:root>
```

**How to reproduce the issue**
Describe how to reproduce the issue and show the current configurations.

- sbt version: 1.8.0
- sbt-sonatype version: 3.9.13

```
$ sbtn
> sonatypeBundleRelease
...
```

**Additional context**
I see that you use `wvlet.log` [here](https://github.com/xerial/sbt-sonatype/blob/9674318ac94ad2f15d9e880bef2684f1e26512ed/src/main/scala/xerial/sbt/Sonatype.scala#L414) and that's probably why the logs are not forwarded to sbt clients. Is it possible to configure `wvlet.log` to forward the logs to the sbt logger in `state.streams.log`?

**Comment by xerial** [comment]
Thanks. I also noticed this issue. airframe-log sends log messages to the standard java.util.logging and stderr, but some sbt-plugins (e.g., sbt-release is one of the examples) may set an unexpected log output target. 

It would be possible to add a log handler to redirect the default logger output to state.streams.log, but as long as there are other plugins that configure java.util.logging, the same problem can still happen, but the impact can be reduced.

Just in case, could you try using the last sbt-sonatype 3.9.17?

**Comment by xerial** [comment]
Confirmed the reproduction. Let me handle this issue in airframe-log https://github.com/wvlet/airframe/issues/2777

**Comment by xerial** [comment]
sbt-sonatype 3.9.18 has been released. This will fix the issue

**Comment by xerial** [comment]
Confirmed the fix is working well with sbtn
![image](https://user-images.githubusercontent.com/57538/224173941-e1d5d68e-6457-44ba-99ce-70553bc58b69.png)

**Comment by adpi2** [comment]
Thanks a lot!
