### ISSUE TITLE
Compile/release for sbt 1.0 beta

### ISSUE THREAD

**Issue by leonardehrenfried** [xerial/sbt-sonatype#45]
sbt 1.0.0-M6 has been released: http://www.scala-sbt.org/1.0/docs/sbt-1.0-Release-Notes.html

Would be great if a compatible version could be published.

In the ideal case it would be a simple cross-compilation but maybe there are incompatibilities that need to be resolved.

**Comment by leonardehrenfried** [comment]
Should have checked the readme first. I am not smart.

**Comment by xerial** [comment]
@leonardehrenfried Thanks for the notice. We still need to create binaries for sbt-1.0.0-M5. I'll upload a new version.

**Comment by xerial** [comment]
Released sbt-sonatype-2.0, which works with sbt-0.13.x, 1.0.0-M5 and M6.
