### ISSUE TITLE
Publish to Maven Central with new interface

### ISSUE THREAD

**Issue by Tammo0987** [xerial/sbt-sonatype#465]
Hello,
I am asking for help. Since it seems like, that the old [Jira](https://issues.sonatype.org/secure/Dashboard.jspa) from Sonatype will be shutdown and only https://central.sonatype.com will be used. I wanted to ask if I can get currently the plugin running with an user token created from the new interface and how I should configure it.

When I use s01.oss.sonatype.org as described, I get an error for to many redirects.

**Comment by rlemaitre** [comment]
I've the same issue. I cannot publish to `central.sonatype.org` due to `too many redirect` errors

**Comment by xerial** [comment]
I wasn't aware of this change: https://central.sonatype.org/register/central-portal/#switching-to-ossrh-during-portal-early-access. In fact, I don't know much about this change and I don't have an account on the new http://central.sonatype.org/ to test it.

It seems Sonatype has renewed almost all steps to register new domains, so I also need to relearn everything from scratch, including its API and token management 😓

**Comment by xerial** [comment]
If you can identify what needs to be fixed in sbt-sonatype and highlight the necessary code changes (for example, a pull request), I would appreciate it. I can create a new release soon.

**Comment by windymelt** [comment]
Almost same issue here (encountered by using sbt-typelevel). Sonatype says they [provide new API for publishing artifacts](https://central.sonatype.org/publish/publish-portal-api/). We may use new endpoint, new API.

I'll check code anyway :)

**Comment by xerial** [comment]
At first glance, it looks like a huge improvement. I'd like to support the new https://central.sonatype.com/ API in sbt-sonatype  4.x

**Comment by Andrapyre** [comment]
See this PR here for an initial implementation that offers Sonatype Central support: https://github.com/xerial/sbt-sonatype/pull/474

**Comment by Andrapyre** [comment]
For users needing immediate support to publish libraries, the following is a temporary workaround:

1. Download the changes in https://github.com/xerial/sbt-sonatype/pull/474.
2. Run 
```sh 
sbt "compile; publishLocal"
```
3. Copy the package id from the output: `<User Dir>/.ivy2/local/org.xerial.sbt/sbt-sonatype/scala_2.12/sbt_1.0/<package-id>/ivys/ivy.xml`
4. Go to your project, checkout a new branch, and add the following to `plugins.sbt` :
```sbt
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "<package-id>")
```
5. In your project, add the following to your `build.sbt`:
```sbt
import xerial.sbt.Sonatype.sonatypeCentralHost

ThisBuild / sonatypeCredentialHost := sonatypeCentralHost
ThisBuild / version := "<target version>"
```
6. Generate credentials in [Sonatype Central](https://central.sonatype.com/account) and add them to your `.zsh` like so: 
```sh
export SONATYPE_USERNAME="<sonatype_username>"
export SONATYPE_PASSWORD="<sonatype_password>"
```
7. If you have not already done so, follow the instructions [here](https://github.com/sbt/sbt-ci-release?tab=readme-ov-file#gpg) to set up GPG. 
8. Run the following and paste in your gpg-generated passphrase when prompted
```
sbt "publishSigned" 
```
9. Run 
```
sbt "sonatypeBundleRelease"
```
10. Go to https://central.sonatype.com/publishing/deployments, verify that all is working as expected with your deployment and publish your component when ready.

**Comment by Andrapyre** [comment]
I was in contact with Taro and he needed some extra time to review this, with one or two further considerations around user flow and naming, which are still TBD. @xerial , could we still get a release commit out in the current form, with a target date for a full 4.0.0 release in a month or two? That way we can gather user feedback while still making clear that setting names, etc. are open to change.

**Comment by Andrapyre** [comment]
@xerial , I have mixed feelings about this new release, as I'd thought that this was permanently blocked and invested effort to create a separate plugin here - https://github.com/lumidion/sbt-sonatype-central with a maintenance and feature roadmap. This plugin is now in its first release...as of a few minutes before https://github.com/xerial/sbt-sonatype/pull/474 was merged. 

The next step to make this feature widely available is to integrate it into `sbt-ci-release`. Do you have bandwidth/interest in maintaining it in this repo? If yes, I will continue with my original plan from several months ago and add the changes to `sbt-ci-release` without introducing the plugin I've created. If not, I would request that this feature be reverted (it has commands that will conflict with the new plugin) and I will integrate the new plugin into `sbt-ci-release` instead.

**Comment by xerial** [comment]
@BillyAutrey Thanks for the heads-up. I haven't followed this discussion thread for a while 😅. Let's close this issue. 

@Andrapyre's comment will be a bit more complicated (due to my capacity and technical difficulties like #548), so it should be discussed elsewhere.
