### ISSUE TITLE
Redirect error on publishSigned

### ISSUE THREAD

**Issue by michaelmior** [xerial/sbt-sonatype#491]
**Describe the bug**
When I try to run `publishSigned`, I get the error below:

```
sbt:JSONoid Discovery> publishSigned
[info] Wrote /home/mmior/apps/jsonoid-discovery/target/scala-2.13/jsonoid-discovery_2.13-0.20.1-0-f8b1bab1-20240620-1043-SNAPSHOT.pom
[info] compiling 1 Scala source to /home/mmior/apps/jsonoid-discovery/target/scala-2.13/classes ...
[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
[info] Main Scala API documentation to /home/mmior/apps/jsonoid-discovery/target/scala-2.13/api...
[info] Main Scala API documentation successful.
[error] stack trace is suppressed; run last publishSigned for the full output
[error] (publishSigned) java.net.ProtocolException: Server redirected too many  times (20)
[error] Total time: 10 s, completed Jun 20, 2024 10:46:05 AM
```

**How to reproduce the issue**
Describe how to reproduce the issue and show the current configurations.

- sbt version: 1.8.2
- sbt-sonatype version: 3.10.0
- Show your build settings:
```
$ sbt
> sonatypeProfileName
io.github.dataunitylab
> sonatypeRepository
https://s01.oss.sonatype.org/service/local
```
- GitHub repository: https://github.com/dataunitylab/jsonoid-discovery.git

**Comment by michaelmior** [comment]
I'm guessing the whole thing is really sbt/sbt-pgp#182

**Comment by michaelmior** [comment]
This seems to have gone away on its own. Either that or I changed something I'm not aware of, but the same credentials that were failing now seem to be working so this is resolved.

**Comment by gueniai** [comment]
@michaelmior I'm on the same boat now. Haven't changed my credentials, just logged into the web interface successfully, yet I'm getting the same redirect error ("java.net.ProtocolException: Server redirected too many  times") 
Can you try to recall what changes you may have done? Anything specific to the credentials file, upgrading any plugin, etc? I'm at my wits end :(

**Comment by michaelmior** [comment]
@gueniai Unfortunately I can't pinpoint what I changed may have had any impact. When things finally worked, I don't believe there were any code or configuration changes on my end.

**Comment by osopardo1** [comment]
same situation here...
@gueniai were you able to solve the problem?
