### ISSUE TITLE
Crossbuild to sbt 2.0.0 + Scala 3

### ISSUE THREAD

**Issue by BillyAutrey** [xerial/sbt-sonatype#523]
**Description**
sbt 2.0.0-M2 is available, so we can start cross-building this to 2.0 and add scala3 support.

**Reproducer**
* Set your sbt version to `2.0.0-M2`
* Add `sbt-sonatype` to your plugin list.
* `sbt compile`

```
[error] Error downloading org.xerial.sbt:sbt-sonatype;sbtVersion=1.0;scalaVersion=3:3.11.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/xerial/sbt/sbt-sonatype_3_1.0/3.11.3/sbt-sonatype-3.11.3.pom
```

**Comment by BillyAutrey** [comment]
Looks like @xuwei-k is working on this already, has a commit as recent as 10 hours ago in https://github.com/xuwei-k/sbt-sonatype/tree/wip-sbt-2

**Comment by xuwei-k** [comment]
- https://github.com/xerial/sbt-sonatype/pull/526

**Comment by xerial** [comment]
Released https://github.com/xerial/sbt-sonatype/releases/tag/v3.12.0
