### ISSUE TITLE
sonatypeOpen doesn't have the effect it seems to have

### ISSUE THREAD

**Issue by djspiewak** [xerial/sbt-sonatype#55]
The `sonatypeOpen` command does create a new staging repo, and it sets up state such that subsequent commands (notably, `sonatypeRelease`) will use *that* repo instead of the auto staged, but it does *not* modify `publishTo`!  It actually has no effect on publication whatsoever, meaning that `publish` and `publishSigned` will always trigger autostaging, and if you have previously used `sonatypeOpen`, the `sonatypeRelease` command will be unable to reference the auto-staged repo (since it was overridden by the manually-opened one that was never used).

The solution here is to go back to defining `publishTo` in the sbt-sonatype plugin.  What we did in sbt-slamdata should be relatively general:

```sbt
publishTo := {
  val nexus = "https://oss.sonatype.org/"
  val profileM = sonatypeStagingRepositoryProfile.?.value

  if (isSnapshot.value) {
    Some("snapshots" at nexus + "content/repositories/snapshots")
  } else {
    val staged = profileM map { stagingRepoProfile =>
      "releases" at nexus +
      "service/local/staging/deployByRepositoryId/" +
      stagingRepoProfile.repositoryId
    }

    staged.orElse(Some("releases" at nexus + "service/local/staging/deploy/maven2"))
  }
}
```

Credit to @drostron on the above.  With this definition of `publishTo`, all currently functional workflows will continue to work, and workflows involving `sonatypeOpen` will spring to life (whereas they currently do not work at all).

**Comment by xerial** [comment]
Thanks for reporting. sbt-sonatype needs to make sure setting this proper publishTo target.

**Comment by jvican** [comment]
I think I reported the same error here: https://github.com/scalacenter/sbt-release-early/issues/18.

**Comment by jvican** [comment]
And even here: https://github.com/xerial/sbt-sonatype/issues/49 :smile:.

**Comment by xerial** [comment]
@jvican I guess making the above publishTo setting suggested by @djspiewak as the default setting of sbt-sonatype is a quick solution, or providing `sonatypePublishTo` settings might be a better idea for people who want to use their own publishTo settings.  

`publishTo := sonatypePublishTo`

**Comment by jvican** [comment]
Oh, absolutely. I think this should be fixed in the plugin. I've been having a look at the code. It seems that redefining `publishTo` would make it work. Would a PR addressing this be welcome? @xerial

**Comment by xerial** [comment]
Yes! Thanks for your help.

**Comment by jvican** [comment]
I couldn't find the time to make the PR, but I fixed this downstream in sbt-release-early, so that users of my plugin are not affected by this issue.

**Comment by xerial** [comment]
@jvican Added a new setting key `sonatypePublishTo` that uses the above suggested fix.
