### ISSUE TITLE
Can't disable root publishing on jvm+js project with sbt 1.0

### ISSUE THREAD

**Issue by loicdescotte** [xerial/sbt-sonatype#57]
I can't disable root publishing on jvm+js project

## steps

`sbt publishSigned`

## problem

Error : `java.lang.RuntimeException: Repository for publishing is not specified.`

## expectation

Sbt should not try to publish root as it is set as `publishArtifact := false`

## notes

sbt version: 1.0
Link to build.sbt : https://github.com/scala-hamsters/hamsters/blob/sbt_1_0/build.sbt

**Comment by xerial** [comment]
I usually add these settings for excluding the root project from publishing:
```
publish := {}
publishLocal := {}
```

**Comment by xerial** [comment]
See https://github.com/wvlet/airframe/blob/c24ec9ad3c505fbe47012efb4105424b0a3326cd/build.sbt#L77 as an example. I have no trouble in publishing jvm+js projects.

**Comment by loicdescotte** [comment]
Hi @xerial , I've tried this and I still have the same error : https://github.com/scala-hamsters/hamsters/blob/sbt_1_0/build.sbt#L20-L24

**Comment by xerial** [comment]
@loicdescotte It seems you are missing publish settings here https://github.com/scala-hamsters/hamsters/blob/sbt_1_0/build.sbt#L75

**Comment by loicdescotte** [comment]
Hi I've tried to define the noPublish setting here too but it still fails with the same error : https://github.com/scala-hamsters/hamsters/blob/sbt_1_0/build.sbt#L77

**Comment by xerial** [comment]
I still don't think this is a problem of sbt-sonatype. How about adding publishTo setting to the common configuration even if noPublish is used?

**Comment by loicdescotte** [comment]
Thanks it worked!

The reason why I think it's a sbt-sonatype issue is that it only occurs
with publishSigned. publishLocal is working well.

Le sam. 2 déc. 2017 à 09:20, Taro L. Saito <notifications@github.com> a
écrit :

**Comment by loicdescotte** [comment]
Should I close the issue or do you think that may be a bug?

**Comment by xerial** [comment]
Ok. Let me close this. Thanks
