### ISSUE TITLE
pom file created in staging is stripped of <developers> entry, cause unknown

### ISSUE THREAD

**Issue by michael-card** [xerial/sbt-sonatype#64]
I am trying to publish to our com.bazaarvoice repository using the sbt plugin and I discovered that when I do a publishLocalSigned the pom files produced are correct but when I do a publishSigned the pom does not include the <developers> entry up in staging and as a result the changes cannot be promoted. Can anyone help me with this, I cannot see what would cause such bizarre behavior. I am attaching all of my scala project files related to the use of the plugin, as well as a copy of one of our poms that I get when I do a publishLocalSigned. The locally published pom is right but the one currently up in our staging directory is missing the <developers> entry for some reason.
[sonatype.sbt.txt](https://github.com/xerial/sbt-sonatype/files/1769030/sonatype.sbt.txt)
[plugins.sbt.txt](https://github.com/xerial/sbt-sonatype/files/1769031/plugins.sbt.txt)
[Commons.scala.txt](https://github.com/xerial/sbt-sonatype/files/1769032/Commons.scala.txt)
[publishSigned-sswf-example_2.10.pom.txt](https://github.com/xerial/sbt-sonatype/files/1769033/publishSigned-sswf-example_2.10.pom.txt)
[publishLocalSigned-sswf-example_2.10.pom.txt](https://github.com/xerial/sbt-sonatype/files/1769034/publishLocalSigned-sswf-example_2.10.pom.txt)

**Comment by xerial** [comment]
@michael-card I guess you need
```
publishMavenStyle := true
```
setting

**Comment by michael-card** [comment]
we already use that setting. As it turns out I can close this issue because the problem was a change in teh publishing logic at Sonatype (maybe a change in the NExus code?) We had to set up a custom staging policy that would not run validation rules on .pom files so we could release. They are still running down what had changed since 8/5/2017 when our repo last published successfully with sbt-sonatype version 2.0. Since I was unable to publish this exact same repo which had not changed and was still using sbt-sonatype 2.0, the change that broke things had to happen in Nexus or someplace else, not the plugin.

**Comment by xerial** [comment]
Actually sbt-sonatype doesn't modify the publishing step of sbt, so you should ask this type of questions in:
https://stackoverflow.com/questions/tagged/sbt
, or use sbt-pgp issue list.

Let me close this ticket.
