### ISSUE TITLE
How to get repository id from publishSigned command

### ISSUE THREAD

**Issue by ChoiByungWook** [xerial/sbt-sonatype#66]
I want to release the staging repository that was created from running publishSigned, however sonatypeRelease will fail if there are more than one repository under the same staging profile. I don't want to release all the repositories, so sonatypeReleaseAll can't be used.

**Comment by xerial** [comment]
You can use these commands:
- sonatypeStagingProfiles
- sonatypeList

**Comment by ChoiByungWook** [comment]
Is there a way to link the repository that was created by publishSigned? If I have two repositories under the same staging profile, how do I differentiate them?

Is there someway we can make publishSigned return the repository id that was just created?

**Comment by xerial** [comment]
You can use sonatypeOpen (session name) https://github.com/xerial/sbt-sonatype/blob/master/workflow.md

**Comment by xerial** [comment]
And also if you set publishTo as:
```
publishTo := soantypePublishTo
```
https://github.com/xerial/sbt-sonatype/blob/master/src/main/scala/xerial/sbt/Sonatype.scala#L84

Then you can send the artifact to the target profile.

**Comment by ChoiByungWook** [comment]
This doesn't seem to work with publishSigned.

I use `sonatypeOpen (profile name) (description)`, which creates a repository in sonatype, but it publishSigned doesn't take any parameters to publish to a specified repository.

**Comment by xerial** [comment]
@ChoiByungWook sbt-sonatype 3.0 has a feature to specify a single staging repository by using sonatypeSessionName key, which is `[sbt-sonatype] (project name) (version)` by default. 

I'm not sure this works for your build configuration, but have a try.
