### ISSUE TITLE
secret key ring doesn't start with secret key tag

### ISSUE THREAD

**Issue by ChoiByungWook** [xerial/sbt-sonatype#67]
Hello,

I am running into this error whenever I attempt to use publishSigned.

(*:signedArtifacts) java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff

The weird thing is that this error is random. For example, whenever I run sbt package before running publishSigned, I run into this error.

**Comment by xerial** [comment]
publishSigned is not a feature of sbt-sonatype. Ask it on Stackoverflow https://stackoverflow.com/questions/tagged/sbt

**Comment by xerial** [comment]
Or using sbt-pgp github issue might be appropriate.
