### ISSUE TITLE
make email/developer optional in ProjectHosting

### ISSUE THREAD

**Issue by raboof** [xerial/sbt-sonatype#68]
For team-maintained projects it doesn't make a lot of sense to include a single developer. Perhaps make it an `Option` or a list?

**Comment by xerial** [comment]
It's Maven central's requirement to have at least one developer entry:
http://central.sonatype.org/pages/requirements.html#developer-information

But adding a factory to allow empty developer list in ProjectHosting seems ok.

**Comment by raboof** [comment]
Ah I didn't realize that! Probably OK in that case then :+1:
