### ISSUE TITLE
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org]

### ISSUE THREAD

**Issue by erikerlandson** [xerial/sbt-sonatype#74]
I've started to upgrade the sbt version and plugin versions for some of my projects, and sbt-sonatype 2.3 `publishSigned` is failing to authenticate against maven central. It's been a while since my last release, not sure what has changed.

slice of error output looks like:
```
[info] Packaging /home/eje/git/isarn-scalatest/target/scala-2.11/isarn-scalatest_2.11-0.0.3.jar ...
[info] Done packaging.
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[warn] CLIENT ERROR: 401 Unauthorized. Check your resolvers username and password.
```
My credentials file still looks like:

```scala
credentials += Credentials("Sonatype Nexus Repository Manager",
                           "oss.sonatype.org",
                           "my-user-name",
                           "my-password")
```
When I log into `oss.sonatype.org` manually, my username and password are still working.

I moved my gpg and sonatype specific config-files into `~/.sbt/1.0-pgp`, and so I am using: 

`$ sbt -Dsbt.global.base=~/.sbt/1.0-pgp +publishSigned` 

as my publish command.

**Comment by xerial** [comment]
I guess this is just the configuration issue of your sbt (build.sbt and files in ~/.sbt/1.0/...) as the error message says the credential is not found. 

Refer to some working examples, 
https://github.com/xerial/sbt-sonatype/blob/master/sonatype.sbt

**Comment by erikerlandson** [comment]
Interesting, it was not finding the config as I assumed it was.  using `~/.sbt/...` instead of `/home/eje/.sbt/...` turns out to cause problems for sbt.

It is now complaining about my `gpgCommand` setting:
```
/home/eje/.sbt/sonatype/global.sbt:1: error: not found: value gpgCommand
gpgCommand := "/usr/bin/gpg"
^
```
But that is progress since it's trying to run my globals file at least.

**Comment by erikerlandson** [comment]
My problems seem to be entirely caused by a combination of `sbt-pgp` configurations being broken, and `sbt.global.base` being broken with '~'.

I switched out `sbt-pgp` for `sbt-gpg`, which seems to be working for me.  You might consider publishing a doc page for using `sbt-gpg` with `sbt-sonatype`.

At any rate, `sbt-sonatype` is _not_ the problem, apologies.

**Comment by xerial** [comment]
Thank you for the confirmation. And also I didn't know about sbt-gpg, https://github.com/jodersky/sbt-gpg.

I'll try this plugin :)
