### ISSUE TITLE
Cross-publish stages each Scala-version to a separate staging repository

### ISSUE THREAD

**Issue by ThijsBroersen** [xerial/sbt-sonatype#78]
When I cross-publish with '+publishSigned' the results are staged in multiple staging repositories (one for each Scala-version). Sometimes it is staged in a single repository. This seems ambiguous. 
If I run 'sonatypeRelease' it fails when multi-repositories are found, but putting 'sonatypeReleaseAll' in my travis-build is not desired as there can be staging repositories (other builds, other projects). 

I looked in the source code and tried some manual testing. It looks like 'sonatypeStagingRepositoryProfile' keeps a reference to a staging-repository. Is it possible to keep multiple references and have 'sonatypeRelease' promote and close this list of staging-repositories?

**Comment by xerial** [comment]
I guess https://github.com/xerial/sbt-sonatype/pull/77 is related.

**Comment by ThijsBroersen** [comment]
> I guess #77 is related.
Not sure, but I apologize I forgot to mention similar issues. E.g. #66 #73 and #49 where is reported about multiple parallel `publishSigned` commands somtimes publish to the same repository.

**Comment by xerial** [comment]
@ThijsBroersen I've redesigned the release flow. By using the flow described here https://github.com/xerial/sbt-sonatype#multi-module-projects, it should be possible to use the same staging repository to publish.
