### ISSUE TITLE
No staging profile found error

### ISSUE THREAD

**Issue by kemitix** [xerial/sbt-sonatype#84]
I'm trying to deploy artifacts within the organisation `net.kemitix.thorp`, using my existing sonatype profile `net.kemitix`. However, I keep getting the error `No staging profile found for net.kemitix.thorp`. I have set both `organization` and `sonatypeProfileName`, but the profile name is being ignored.

* My [build.sbt](https://github.com/kemitix/thorp/blob/master/build.sbt)

I'm concerned that [this line](https://github.com/xerial/sbt-sonatype/blob/master/src/main/scala/xerial/sbt/Sonatype.scala#L53) might be causing my setting to be ignored.

**Comment by xerial** [comment]
I think you need to check the result of `$ sbt sonatypeProfileName` to see what configuration is effective in your build.

**Comment by kemitix** [comment]
@xerial 
I get:
```
[info] storage-api / sonatypeProfileName
[info] 	net.kemitix.thorp
[info] core / sonatypeProfileName
[info] 	net.kemitix.thorp
[info] thorp-lib / sonatypeProfileName
[info] 	net.kemitix.thorp
[info] storage-aws / sonatypeProfileName
[info] 	net.kemitix.thorp
[info] domain / sonatypeProfileName
[info] 	net.kemitix.thorp
[info] cli / sonatypeProfileName
[info] 	net.kemitix.thorp
[info] sonatypeProfileName
[info] 	net.kemitix.thorp
```

**Comment by xerial** [comment]
Then you need to include sonatypeProfileName setting to the common setting so that every project can look at that value.

**Comment by kemitix** [comment]
Thanks. `sbt sonatypeProfileName` is showing me what I want to see now.
