### ISSUE TITLE
What are changes after 2.4 ?

### ISSUE THREAD

**Issue by exoego** [xerial/sbt-sonatype#88]
2.5, 2.6 and 3.0 are missing in the release notes
https://github.com/xerial/sbt-sonatype/blob/master/ReleaseNotes.md

Is there any breaking change in 3.0?

**Comment by xerial** [comment]
2.5 fixes issue #79 
2.6 added sonatypeDropAll

3.0 added a new workflow support (using sonatypePrepare) for making releases more safe and convenient: https://github.com/xerial/sbt-sonatype/commit/81adb9fd7130d4f0b1e03b6aa562fae9115f924c

**Comment by xerial** [comment]
Updated release notes https://github.com/xerial/sbt-sonatype/blob/master/ReleaseNotes.md

**Comment by exoego** [comment]
Thanks for quick responding !!
