### ISSUE TITLE
Support bundle upload 

### ISSUE THREAD

**Issue by xerial** [xerial/sbt-sonatype#89]
Using publishSigned to directly to Sonatype API is quite slow if we need to upload hundreds of artifacts. 

Instead, it seems we can use the bundle upload PUT API of sonatype (Discussed in #83)

A possible approach:
- Do publishLocalSigned to some staging local folder (e.g., target/staging)
- Create a local bundle (= a zipped(?) collection) of local artifacts. Nexus ant-plugin has zapper to create a bundle from a directory: https://github.com/sonatype/nexus-ant-tasks/blob/master/nexus-staging-ant-tasks/src/main/java/org/sonatype/nexus/ant/staging/deploy/ZapperImpl.java#L40
- Upload it using the bundle upload API
- Do the regular close/promote step at Sonatype API

Related:
- https://repository.sonatype.org/nexus-staging-plugin/default/docs/path__staging_bundle_upload.html
- https://github.com/sonatype/nexus-ant-tasks/blob/master/nexus-staging-ant-tasks/src/main/java/org/sonatype/nexus/ant/staging/deploy/AbstractDeployTask.java#L111

**Comment by pshirshov** [comment]
This is also related (and most likely reusable): https://github.com/sonatype/spice-zapper/tree/master/src/main/java/org/sonatype/spice/zapper

This thing is under the hood of the ant library and it can pack artifacts into several bundles and upload them concurrently.

**Comment by xerial** [comment]
Right. It seems using zapper is quite easy. 

I'm now thinking how to set publishTo target for publishSignedLocal to target/staging folder

**Comment by pshirshov** [comment]
That's what I do for my projects (unfortunately, stating works for releases only, I may be wrong but I didn't find a way to publish snapshots this way):

```
    publishTo := (if (!isSnapshot.value) {
        Some(Resolver.file("local-publish", new File("target/local-repo")))
      } else {
        Some(Opts.resolver.sonatypeSnapshots)
      })
```

I guess you may just add similar thing into `projectSettings`

**Comment by xerial** [comment]
No worries. It's possible to dynamically configure publishTo by using sbt command (as sonatypePrepare already doing that). 

I'm now testing how bundle upload work

**Comment by xerial** [comment]
Good news. Uploading 1000s of files using a bundle finished within a minute!

**Comment by pshirshov** [comment]
Just as planned. You are welcome :3

**Comment by xerial** [comment]
Released sbt-sonatype 3.1 with bundle upload support. Many thanks @pshirshov

**Comment by adamw** [comment]
Updated https://github.com/softwaremill/sbt-softwaremill with the latest sbt-sonatype. So far bundle-publishing of the plugin itself went great. This will really make working with OSS much easier :) Thanks!

**Comment by pshirshov** [comment]
@xerial : I guess you should put a snippet like this into the doc:

First enable bundle publishing for you release configuration

```scala
publishTo in ThisBuild := (if (!isSnapshot.value) {
  sonatypePublishToBundle.value
} else {
  Some(Opts.resolver.sonatypeSnapshots)
})
```

Then use `sonatypeBundleRelease`:

```bash
sbt +clean +sonatypeBundleClean +publishSigned +sonatypeBundleRelease
```

**Comment by xerial** [comment]
@pshirshov sonatypePublishToBundle is almost the same as what you mentioned. 

I think this is a little bit an off-topic for this thread. We should use a different ticket.

**Comment by adamw** [comment]
@pshirshov what worked for me is `sonatypeBundleRelease` + the `publishTo` setting, see https://github.com/softwaremill/sbt-softwaremill/blob/master/src/main/scala/com/softwaremill/Publish.scala#L29 lines 29 and 85
